version: '3'
services:
  docker-mysql:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: cookbook
    ports:
      - '3307:3306'
    volumes:
      - ./data:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", 'mysqladmin ping']
      timeout: 20s
      retries: 10

  app:
    restart: on-failure
    build: ./
    expose:
      - "8080"
    ports:
      - 8080:8080
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://docker-mysql:3306/cookbook?useUnicode=true&serverTimezone=UTC
    depends_on:
      docker-mysql:
        condition: service_healthy